<?php

namespace App\Services\Asterisk;

use App\Models\Did;
use Illuminate\Support\Facades\Log;

/**
 * Turns the SIP details saved on a DID into Asterisk PJSIP objects (auth, aor,
 * endpoint, identify, outbound registration), writes them to an included config
 * file and reloads PJSIP. Also reads the registration state back from Asterisk.
 * Only validated values reach the file; secrets never leave the server.
 */
class TrunkProvisioner
{
    public function __construct(private AsteriskAMIService $ami)
    {
    }

    public function isDryRun(): bool
    {
        return (bool) config('broadcast.asterisk.dry_run');
    }

    public function dialString(Did $did): string
    {
        return 'PJSIP/{number}@'.$did->sipName();
    }

    /** Write the config for every active DID that has SIP details and reload PJSIP. Returns an error message or null. */
    public function apply(): ?string
    {
        if ($this->isDryRun()) {
            return null;
        }

        $file = config('broadcast.asterisk.pjsip_file');
        if (@file_put_contents($file, $this->render(), LOCK_EX) === false) {
            Log::error('Cannot write PJSIP config', ['file' => $file]);

            return "Cannot write {$file} (check file permissions).";
        }
        foreach (['res_pjsip.so', 'res_pjsip_outbound_registration.so'] as $module) {
            if (! $this->ami->command("module reload {$module}")) {
                return 'Config saved, but Asterisk could not be reloaded (AMI unreachable or no "command" permission).';
            }
        }

        return null;
    }

    public function render(): string
    {
        $transport = config('broadcast.asterisk.pjsip_transport');
        $out = "; Generated by Voice Broadcast. Do not edit: changes are overwritten.\n";

        foreach (Did::where('status', 'active')->whereNotNull('sip_host')->whereNotNull('sip_username')->orderBy('id')->get() as $d) {
            $n = $d->sipName();
            $host = $d->sip_host;
            $port = $d->sip_port;
            $user = $d->sip_username;
            $pass = $this->escape((string) $d->sip_password);
            $out .= <<<CONF

; DID {$d->number}
[{$n}-auth]
type=auth
auth_type=userpass
username={$user}
password={$pass}

[{$n}]
type=aor
contact=sip:{$host}:{$port}
qualify_frequency=60

[{$n}]
type=endpoint
transport={$transport}
context=broadcast
disallow=all
allow=ulaw,alaw
outbound_auth={$n}-auth
aors={$n}
from_user={$user}
from_domain={$host}
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[{$n}]
type=identify
endpoint={$n}
match={$host}

[{$n}-reg]
type=registration
transport={$transport}
outbound_auth={$n}-auth
server_uri=sip:{$host}:{$port}
client_uri=sip:{$user}@{$host}:{$port}
contact_user={$user}
retry_interval=60
forbidden_retry_interval=300
expiration=3600

CONF;
        }

        return $out;
    }

    /** ';' starts a comment in Asterisk configs; backslash-escape it. Values are validated to have no newlines. */
    private function escape(string $v): string
    {
        return str_replace(['\\', ';'], ['\\\\', '\\;'], $v);
    }

    /**
     * Read the outbound registration state of every DID from Asterisk and store it.
     * Returns false when Asterisk could not be queried.
     */
    public function refreshStatuses(): bool
    {
        $dids = Did::whereNotNull('sip_host')->get();
        if ($dids->isEmpty()) {
            return true;
        }
        if ($this->isDryRun()) {
            return false;
        }

        $events = $this->ami->eventList(['Action' => 'PJSIPShowRegistrationsOutbound']);
        if ($events === null) {
            Did::whereNotNull('sip_host')->update(['sip_status' => 'unreachable', 'sip_status_detail' => 'Asterisk is not reachable.', 'sip_checked_at' => now()]);

            return false;
        }

        $byName = collect($events)->where('Event', 'OutboundRegistrationDetail')->keyBy(fn ($e) => $e['ObjectName'] ?? '');
        foreach ($dids as $d) {
            $e = $byName[$d->sipName().'-reg'] ?? null;
            if (! $d->isActive()) {
                [$status, $detail] = ['inactive', 'DID is inactive, not registered.'];
            } elseif (! $e) {
                [$status, $detail] = ['pending', 'Waiting for Asterisk to load the registration.'];
            } else {
                $raw = strtolower($e['Status'] ?? 'unregistered');
                $status = in_array($raw, ['registered', 'rejected', 'unregistered'], true) ? $raw : 'pending';
                $detail = match ($status) {
                    'registered' => 'Registered with '.$d->sip_host.'.',
                    'rejected' => 'The SIP server rejected the registration (check username / password / host).',
                    'unregistered' => 'Not registered yet, or the server is not answering.',
                    default => 'Registration state: '.($e['Status'] ?? 'unknown'),
                };
            }
            $d->forceFill(['sip_status' => $status, 'sip_status_detail' => $detail, 'sip_checked_at' => now()])->save();
        }

        return true;
    }
}
